import { a11yHasExpectedHtml, a11yInitialHtml, hasReturnVal, loadTestPage } from "../../support"

export const increments_0_1 = () => {
	describe('increments 0-1', () => {
		it('0 0 0 0 A', () => {
			loadTestPage({ segment: 'hrs12' })
				.type('0')
				.should('have.value', '12:30 PM')
				.then(a11yHasExpectedHtml('<p>12.</p>'))
				.then(hasReturnVal('12:30'))
				.type('0')
				.should('have.value', '12:30 PM')
				.then(a11yHasExpectedHtml(a11yInitialHtml().minutes))
				.then(hasReturnVal('12:30'))
				.type('0')
				.should('have.value', '12:00 PM')
				.then(a11yHasExpectedHtml('<p>0.</p>'))
				.then(hasReturnVal('12:00'))
				.type('0')
				.should('have.value', '12:00 PM')
				.then(a11yHasExpectedHtml(a11yInitialHtml().mode))
				.then(hasReturnVal('12:00'))
				.type('a')
				.should('have.value', '12:00 AM')
				.then(a11yHasExpectedHtml('<p>AM.</p>'))
				.then(hasReturnVal('00:00'))
		})
		it('1 1 1 1 A', () => {
			loadTestPage({ segment: 'hrs12' })
				.type('1')
				.should('have.value', '01:30 PM')
				.then(a11yHasExpectedHtml('<p>1.</p>'))
				.then(hasReturnVal('13:30'))
				.type('1')
				.should('have.value', '11:30 PM')
				.then(a11yHasExpectedHtml(a11yInitialHtml().minutes))
				.then(hasReturnVal('23:30'))
				.type('1')
				.should('have.value', '11:01 PM')
				.then(a11yHasExpectedHtml('<p>1.</p>'))
				.then(hasReturnVal('23:01'))
				.type('1')
				.should('have.value', '11:11 PM')
				.then(a11yHasExpectedHtml(a11yInitialHtml().mode))
				.then(hasReturnVal('23:11'))
				.type('a')
				.should('have.value', '11:11 AM')
				.then(a11yHasExpectedHtml('<p>AM.</p>'))
				.then(hasReturnVal('11:11'))
		})
	})
}