import { cyInput, cySelectSegment, hasReturnVal, loadTestPage, use } from "../support"

describe('Button tests', () => {
	button_1()
	button_2()
	button_3()

	function button_1() {
		it('Button 1', () => {
			loadTestPage().then(() => cy.get('#Forced-polyfill-button-1').click().then(() =>
				cyInput().should('have.value', '07:15 AM').then(hasReturnVal('07:15')).then(() =>
					// Need to make sure the basic functions still work after clicking a button
					cySelectSegment('hrs12')
						.then(use.upArrow)
						.should('have.value', '08:15 AM')
						.then(use.downArrow)
						.then(use.downArrow)
						.should('have.value', '06:15 AM')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '06:16 AM')
						.then(use.downArrow)
						.then(use.downArrow)
						.should('have.value', '06:14 AM')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '06:14 PM')
						.then(use.downArrow)
						.should('have.value', '06:14 AM')
						.then(use.del)
						.should('have.value', '06:14 --')
						.then(use.leftArrow)
						.then(use.backspace)
						.should('have.value', '06:-- --')
						.then(use.leftArrow)
						.then(use.del)
						.should('have.value', '--:-- --')
				)
			))
		})
	}
	function button_2() {
		it('Button 2', () => {
			loadTestPage().then(() => cy.get('#Forced-polyfill-button-2').click().then(() =>
				cyInput().should('have.value', '03:45 PM').then(hasReturnVal('15:45')).then(() =>
					cySelectSegment('hrs12')
						.then(use.upArrow)
						.should('have.value', '04:45 PM')
						.then(use.downArrow)
						.then(use.downArrow)
						.should('have.value', '02:45 PM')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '02:46 PM')
						.then(use.downArrow)
						.then(use.downArrow)
						.should('have.value', '02:44 PM')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '02:44 AM')
						.then(use.downArrow)
						.should('have.value', '02:44 PM')
						.then(use.del)
						.should('have.value', '02:44 --')
						.then(use.leftArrow)
						.then(use.backspace)
						.should('have.value', '02:-- --')
						.then(use.leftArrow)
						.then(use.del)
						.should('have.value', '--:-- --')
				)
			))
		})
	}
	function button_3() {
		it('Button 3', () => {
			loadTestPage().then(() => cy.get('#Forced-polyfill-button-3').click().then(() =>
				cyInput().should('have.value', '--:-- --').then(hasReturnVal('')).then(() =>
					cySelectSegment('hrs12')
						.then(use.upArrow)
						.should('have.value', '01:-- --')
						.then(use.downArrow)
						.should('have.value', '12:-- --')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '12:01 --')
						.then(use.downArrow)
						.then(use.downArrow)
						.should('have.value', '12:59 --')
						.then(use.rightArrow)
						.then(use.upArrow)
						.should('have.value', '12:59 AM')
						.then(use.downArrow)
						.should('have.value', '12:59 PM')
						.then(use.del)
						.should('have.value', '12:59 --')
						.then(use.leftArrow)
						.then(use.backspace)
						.should('have.value', '12:-- --')
						.then(use.leftArrow)
						.then(use.del)
						.should('have.value', '--:-- --')
				)
			))
		})
	}
})